---
# file: marathon/tasks/main.yml
# Installs Marathon on CoreOS

- name: register marathon service installed (boolean)
  stat: path="/etc/systemd/system/marathon.service"
  register: marathon_service_installed

- include: "install-CoreOS.yml"
  when: ansible_os_family == "CoreOS" and "master" in mesos_install_mode

- include: "uninstall-CoreOS.yml"
  when: ansible_os_family == "CoreOS" and {{ marathon_service_installed.stat.exists }} and "master" not in mesos_install_mode


