---
# file: main.yml
# do something

- name: "a play that installs new user services to the cluster"
  hosts: "jenkins_master_hosts"
  gather_facts: "true"
  serial: 1

  handlers:
  - include: handlers/main.yml

  roles:
  - jenkins
